name: CI

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  test-kubernetes:
    name: Test Kubernetes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test
        run: sudo bash kubernetes.sh

      - name: Test override
        run: sudo KUBECTL_VERSION=v1.25.4 bash kubernetes.sh

  test-openshift:
    name: Test Openshift
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test
        run: sudo bash openshift.sh

      - name: Test override
        run: sudo OPERATOR_SDK_VERSION=v1.34.1 bash openshift.sh

  test-k9s:
    name: Test k9s
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test
        run: sudo bash k9s.sh -y

      - name: Test k9s override
        run: sudo K9S_VERSION=v0.32.4 bash k9s.sh -y

  test-krew:
    name: Test krew
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test
        run: sudo bash krew.sh -y

      - name: Test krew override
        run: sudo KREW_VERSION=v0.4.4 bash krew.sh -y